import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
    return (
        <div className="flex min-h-screen flex-col items-center justify-center py-2">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
                <h1 className="text-6xl font-bold">
                    Welcome to{" "}
                    <a className="text-blue-600" href="https://nextjs.org">
                        Next.js!
                    </a>
                </h1>

                <p className="my-6 text-2xl">
                    Get started by editing{" "}
                    <code className="rounded-md bg-gray-100 p-3 font-mono text-lg">
                        pages/index.js
                    </code>
                </p>

                <div className="mt-12 flex space-y-8 max-w-3xl flex-wrap sm:w-full">
                    <div className="flex space-x-8">
                        <a
                            href="https://nextjs.org/docs"
                            className="w-1/2 rounded-xl border flex-initial p-6 text-left transition-colors hover:text-blue-600 focus:text-blue-600"
                        >
                            <h3 className="mb-6 text-2xl font-bold">Documentation &rarr;</h3>
                            <p>Find in-depth information about Next.js features and API.</p>
                        </a>

                        <a
                            href="https://nextjs.org/learn"
                            className="w-1/2 rounded-xl border flex-initial p-6 text-left transition-colors hover:text-blue-600 focus:text-blue-600"
                        >
                            <h3 className="mb-6 text-2xl font-bold">Learn &rarr;</h3>
                            <p>Learn about Next.js in an interactive course with quizzes!</p>
                        </a>
                    </div>
                    <div className="flex space-x-8">
                        <a
                            href="https://github.com/vercel/next.js/tree/master/examples"
                            className="w-1/2 rounded-xl border flex-initial p-6 text-left transition-colors hover:text-blue-600 focus:text-blue-600"
                        >
                            <h3 className="mb-6 text-2xl font-bold">Examples &rarr;</h3>
                            <p>Discover and deploy boilerplate example Next.js projects.</p>
                        </a>
                        <a
                            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                            className="w-1/2 rounded-xl border flex-initial p-6 text-left transition-colors hover:text-blue-600 focus:text-blue-600"
                        >
                            <h3 className="mb-6 text-2xl font-bold">Deploy &rarr;</h3>
                            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
                        </a>
                    </div>
                </div>
            </main>

            <footer className="flex h-24 w-full items-center justify-center border-t">
                <a
                    className="flex items-center justify-center gap-2"
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </a>
            </footer>
        </div>
    );
};

export default Home;
