name: Lighthouse CI
on:
    push:
        branches: [master]
jobs:
    lighthouse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Audit URLs using Lighthouse
              uses: treosh/lighthouse-ci-action@v9
              with:
                  urls: |
                      https://evanm.io
                  uploadArtifacts: false
                  temporaryPublicStorage: true
                  runs: 3
